#!/bin/sh

npx vitest run tests/unit/specs/alertText.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlAlerta.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlAlerta002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlAlertaOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlAlertmanager.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlAlertmanager002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlChatwork.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlCommand.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlDatadog.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlDingtalk.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlDingtalk002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlDingtalk003.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlDingtalk004.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlDiscord.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlDiscordOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlEmail.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlEmail002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlExotel.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlFlashduty001.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlFlashduty002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlFlashduty003.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlFlashduty004.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlGelf001.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlGelf002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlGitter.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlGitterOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlGoogleChat.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlGoogleChat002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlHttpPost.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlHttpPost002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlHttpPostOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlHttpPost2.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlHttpPost2Opt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlIris.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlIris002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlJira.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlLark.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlLineMessageApi.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMattermost.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMattermost002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMatrixhookshot001.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMatrixhookshot002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMsTeams.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMsTeamsOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMsPowerAutomate001.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlMsPowerAutomate002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlOpsgenie.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlOpsgenie002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlOpsgenie003.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlOpsgenie004.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlOpsgenie005.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlOpsgenie006.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlPagerDuty.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlPagerDuty002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlPagerDuty003.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlPagerDuty004.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlPagerDuty005.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlPagerTree.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlRocketChat.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlRocketChat002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlServiceNow.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlSes.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlSesProfile.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlSlack.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlSlack002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlSns.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlSnsProfile.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlStomp.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlStompModRequiredAndOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTelegram001.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTelegram002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTelegram003.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTencentSms.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTencentSmsOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTheHive.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTheHiveOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTwilioCopilot.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlTwilioSms.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlVictorOps.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlVictorOpsOpt.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlWebex001.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlWebex002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlWorkWeChat.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlYzj001.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlYzj002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlWorkWeChat002.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlZabbix.spec.js &&
npx vitest run tests/unit/specs/alert/ConfigYamlZabbixSenderHostPort.spec.js &&
npx vitest run tests/unit/specs/ConfigYamlScanEntireTimefame.spec.js &&
npx vitest run tests/unit/specs/luceneSyntaxBuilder.spec.js

# TODO: Tests that fail
# npx vitest run tests/unit/specs/ConfigCondition.spec.js
# npx vitest run tests/unit/specs/ConfigAlert.spec.js
# npx vitest run tests/unit/specs/ConfigYaml.spec.js
# npx vitest run tests/unit/specs/ErrorsLog.spec.js
# npx vitest run tests/unit/specs/QueriesLog.spec.js
# npx vitest run tests/unit/specs/RuleView.spec.js 
# npx vitest run tests/unit/specs/SilenceLog.spec.js    